import localFont from "next/font/local";
import Link from "next/link";
import style from "./rootStyle.module.css";
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Globalmantics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
            <h2><Link className={style.homeLink} href="/home">Globalmantics</Link></h2>
            <h2><Link className={style.menuLink} href="/blog">Blog</Link></h2>
            <h2><Link className={style.menuLink} href="conference">Conference</Link></h2>
            <h2> <Link className={style.menuLink} href="setting">Setting</Link></h2>
        </header>
        {children}
      </body>
    </html>
  );
}
